kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ClusterCreateOps
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods, podlogs"]
  verbs: ["get", "watch", "list", "exec", "admin", "create", "patch"]
  nonResourceURLs: ["*"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# This role binding allows members in group DevOpsGroup to pod-list-podlogs-list in the "devops" namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ClusterCreateOps
subjects:
- kind: Group
  name: "ClusterCreateOps" # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: ClusterCreateOps # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io