apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8cluster-role-grantor
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["bind"]
  resourceNames: ["admin","edit","view"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8cluster-cluster-role-grantor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8cluster-role-grantor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: K8Cluster-RoleGrantor